### Get all games
GET localhost:44376/api/Games/

### Get game by ID
GET localhost:44376/api/Games/19

### Add player to Game with specific ID
POST localhost:44376/api/Games/AddPlayer
Content-Type: application/json
//apikey: apikey1234_visitor
 
{
    "GameId": 4,
    "PlayerName": "Ludo Player 3",
    "PlayerColor": "Red"
}

### Create new game
POST localhost:44376/api/Games/New
Content-Type: application/json
 
{
    "ID": 1,
    "PlayerName":"Player1",
    "PlayerColor":"Yellow"
}

### Start game
POST localhost:44376/api/Games/StartGame
Content-Type: application/json

19

### Get LudoData
GET localhost:44376/api/Games/LudoData

### RollDie
POST localhost:44376/api/Gameplay/RollDie
Content-Type: application/json
 
{
    "GameId": 1,
    "PlayerId": 1
}

### ChooseAction
POST localhost:44376/api/Gameplay/ChooseAction
Content-Type: application/json
 
1

### GetMoveActions
POST localhost:44376/api/Gameplay/GetMoveActions
Content-Type: application/json
 
{
    "GameId": 1,
    "PlayerId": 1
}